
var EntityIndex = 0;  // 食物、身体、头 生成id
var PI = 3.1415925

var INVALID_ENTITY_ID = -1;

var SNAKE_ENEMY_INIT_NUM = 10;
var SNAKE_INIT_LENGTH = 5;
var SNAKE_MOVE_INTERVAL = 0.03;
var SNAKE_CLIP_PATH_INTERVAL = 0.5;
var SNAKE_LEFT_MIN_EMPTYBODY_POS = 5;
var RANDOM_FOOD_INTERVAL = 0.3;
var MAX_FOOD_NUM = 100;
var NORMAL_AI_UPDATE_INTERVAL = 0.2;
var SNAKE_CHANGE_SIZE_INTERVAL = 1.0;

var SNAKE_SCALE_MIN_LENGTH = 20;
var SNAKE_SCALE_ADD_MAX_LENGTH = 180;
var SNAKE_SCALE_MIN_SCALE = 1.0;
var SNAKE_SCALE_ADD_MAX_SCALE = 1.0;
var SNAKE_SCALE_MIN_PATH_INTERVAL = 6;
var SNAKE_SCALE_ADD_MAX_PATH_INTERVAL = 6;

var FOOD_STAR_RANDOM_CHANCE = 0.02;
var FOOD_STAR_SPEED = 200;

var MAX_EAT_RANGE = 30.0;

var MAP_WIDTH = 2048.0;
var MAP_HEIGHT = 1536.0;

var LENGTH_TO_SCORE = 6;

var MAP_REGION_WIDTH = 400.0;
var MAP_REGION_HEIGHT = 400.0;

var REGION_TYPE_FOOD = 1;
var REGION_TYPE_SKANE = 2;